c_compiler_version:        # [linux-64]
  - 13.2.0                 # [linux-64]

cxx_compiler_version:      # [linux-64]
  - 13.2.0                 # [linux-64]

fortran_compiler_version:  # [linux-64]
  - 13.2.0                 # [linux-64]
