c_compiler_version:        # [target_platform == 'linux-64']
  - 13.2.0                 # [target_platform == 'linux-64']

cxx_compiler_version:      # [target_platform == 'linux-64']
  - 13.2.0                 # [target_platform == 'linux-64']

fortran_compiler_version:  # [target_platform == 'linux-64']
  - 13.2.0                 # [target_platform == 'linux-64']
