{% set mvapich_version = "4.1" %}
{% set shs_libfabric_version = "2.2.0" %}
{% set cuda_version = "12.6" %}
{% set gdrcopy_version = "2.5.1" %}
{% set build = 4 %}

package:
  name: mvapich
  version: {{ mvapich_version }}

source:
  - url: https://github.com/NVIDIA/gdrcopy/archive/refs/tags/v{{ gdrcopy_version }}.tar.gz
    sha256: c6d5ebb7dabb89d798f27609511735595004da73af28d93ac041bb5290c4cbec
    folder: gdrcopy
  - url: https://mvapich.cse.ohio-state.edu/download/mvapich/mv2/mvapich-{{ mvapich_version }}.tar.gz
    sha256: a36c459befd5b0d1b66e4a217250d89d9f77b903fcc4a050efddb1c475b8dcab
    folder: mvapich
    patches:
      - fix_ucr_domain.patch
      - fix_cuda_computeMode.patch 
  - url: https://github.com/HewlettPackard/shs-libfabric/archive/refs/tags/v{{ shs_libfabric_version }}.tar.gz
    sha256: 734aa46fc1a5c69c59514aade3e8f17037506fbb08013f4be63d669e546570b0 
    folder: shs-libfabric
    patches:
      - fix_reallocarray.patch 
      - define_map_huge_shift.patch

build:
  number: {{ build }}
  string: shs_cuda_h{{ PKG_HASH }}_{{ build }}
  skip: true  # [win or osx] 
  script_env:
    - LIBS=""
  run_exports:
    - {{ pin_subpackage('mvapich', max_pin='x.y') }}
    - {{ pin_compatible('cuda-version', min_pin='x', max_pin='x') }}  
  missing_dso_whitelist:
    - $RPATH/libcuda.so.*
    - $RPATH/libcuda.so.1
    - libcuda.so.*
    - libcuda.so.1
  ignore_run_exports:
    - cuda-cudart-dev

requirements:
  build:
    - autoconf
    - automake
    - bison
    - {{ compiler('c') }} 
    - {{ compiler('cxx') }} 
    - {{ compiler('fortran') }} 
    - {{ stdlib("c") }}
    - libtool
    - make
    - patchelf
    - pkg-config
    - cuda-nvcc {{ cuda_version }}.*
  host:
    - cuda-cudart-dev {{ cuda_version }}.*
    - cuda-nvcc {{ cuda_version }}.*
    - cuda-nvvm {{ cuda_version }}.*  
    - cuda-nvml-dev {{ cuda_version }}.*
    - cuda-version {{ cuda_version }}.*
    - json-c
    - libcurl
    - libhwloc
    - libnl
    - rdma-core 
    - shs-cassini-headers
    - shs-cxi-drivers
    - shs-libcxi
    - ucx
  run:
    - cuda-crt-dev_linux-64 {{ cuda_version }}.*  # [target_platform == 'linux-64']
    - cuda-crt-dev_linux-aarch64 {{ cuda_version }}.*  # [target_platform == 'linux-aarch64']
    - cuda-cudart_linux-64 {{ cuda_version }}.*  # [target_platform == 'linux-64']
    - cuda-cudart_linux-aarch64 {{ cuda_version }}.*  # [target_platform == 'linux-aarch64']
    - cuda-cudart-dev {{ cuda_version }}.*
    - cuda-driver-dev {{ cuda_version }}.*
    - cuda-nvcc {{ cuda_version }}.*
    - json-c
    - libcurl
    - libhwloc
    - libnl
    - mpi 1.0.* mvapich
    - rdma-core
    - shs-libcxi
    - ucx

test:
  requires:
    - {{ compiler('c') }}
  commands:
    - test -f $CONDA_PREFIX/lib/libmpi.so
    - test -f $CONDA_PREFIX/lib/libmpifort.so
    - test -f $CONDA_PREFIX/bin/mpicc
    - test -f $CONDA_PREFIX/bin/mpifort
    - test -f $CONDA_PREFIX/bin/mpiexec

about:
  home: https://mvapich.cse.ohio-state.edu/
  license: BSD-3-Clause AND MIT AND (BSD-2-Clause OR GPL-2.0-only)
  license_family: BSD
  license_file:
    - mvapich/COPYRIGHT
    - shs-libfabric/COPYING
    - gdrcopy/LICENSE
  summary: MVAPICH, a high-performance MPI library by The Ohio State University.
  description: |
    MVAPICH is a high-performance implementation of the MPI (Message Passing Interface) standard 
    with support for **both** Unified Communication X (UCX) and Open Fabric Interfaces (OFI).

    The MVAPICH-SHS variant comes with the CXI provider support for Slingshot Host Systems and
    the `_cuda` version was build with CUDA 12 support (use `MPIR_CVAR_ENABLE_GPU=0` to *disable* it).

    In case the actual *netmod* is not correctly recognized at run time, activate it using either
    `MPICH_CH4_NETMOD=ucx` or `MPICH_CH4_NETMOD=ofi`.

extra:
  recipe-maintainers:
    - j34ni
