{% set version = "3.0" %}

package:
  name: mvapich
  version: {{ version }}

source:
  url: https://mvapich.cse.ohio-state.edu/download/mvapich/mv2/mvapich-{{ version }}.tar.gz
  sha256: ee076c4e672d18d6bf8dd2250e4a91fa96aac1db2c788e4572b5513d86936efb

build:
  number: 0
  skip: true  # [win or osx]
  run_exports:
    - {{ pin_subpackage('mvapich', max_pin='x.y') }}

requirements:
  build:
    - bison
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - make
  host:
    - libhwloc
    - rdma-core  # [linux]
  run:
    - mpi 1.0.* mvapich

test:
  commands:
    - mpiexec -n 2 $PREFIX/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency -m 1024:1024

about:
  home: https://mvapich.cse.ohio-state.edu/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYRIGHT
  summary: MVAPICH, a high-performance MPI library by The Ohio State University.

extra:
  recipe-maintainers:
    - j34ni
