{% set mvapich_version = "4.1" %}
{% set shs_libfabric_version = "2.2.0" %}
{% set build = 13 %}

package:
  name: mvapich
  version: {{ mvapich_version }}

source:
  - url: https://mvapich.cse.ohio-state.edu/download/mvapich/mv2/mvapich-{{ mvapich_version }}.tar.gz
    sha256: 25a53d3725b669e2c648158fb7c9fc5b1388953f3a2f949748586c447d0e43ee
    folder: mvapich
    patches:
      - fix_ucr_domain.patch
  - url: https://github.com/HewlettPackard/shs-libfabric/archive/refs/tags/v{{ shs_libfabric_version }}.tar.gz
    sha256: 734aa46fc1a5c69c59514aade3e8f17037506fbb08013f4be63d669e546570b0 
    folder: shs-libfabric
    patches:
      - fix_reallocarray.patch 
      - define_map_huge_shift.patch

build:
  number: {{ build }}
  string: shs_h{{ PKG_HASH }}_{{ build }}
  skip: true  # [win or osx] 
  run_exports:
    - {{ pin_subpackage('mvapich', max_pin='x.y') }}

requirements:
  build:
    - autoconf
    - automake
    - bison
    - {{ compiler('c') }} 
    - {{ compiler('cxx') }} 
    - {{ compiler('fortran') }} 
    - {{ stdlib("c") }}
    - libtool
    - make
    - patchelf
    - pkg-config
  host:
    - json-c
    - libcurl
    - libhwloc
    - libnl
    - rdma-core 
    - shs-cassini-headers
    - shs-cxi-drivers
    - shs-libcxi
    - ucx
  run:
    - json-c
    - libcurl
    - libhwloc
    - libnl
    - mpi 1.0.* mvapich
    - rdma-core
    - shs-libcxi
    - ucx

test:
  requires:
    - {{ compiler('c') }}
  files:
    - hello.c
  commands:
    - test -f $CONDA_PREFIX/lib/libmpi.so
    - test -f $CONDA_PREFIX/lib/libmpifort.so
    - test -f $CONDA_PREFIX/bin/mpicc
    - test -f $CONDA_PREFIX/bin/mpifort
    - test -f $CONDA_PREFIX/bin/mpiexec
    - $CONDA_PREFIX/bin/mpicc -o hello_mpi hello.c
    - $CONDA_PREFIX/bin/mpiexec -np 2 ./hello_mpi

about:
  home: https://mvapich.cse.ohio-state.edu/
  license: BSD-3-Clause AND (BSD-2-Clause OR GPL-2.0-only)
  license_family: BSD
  license_file:
    - mvapich/COPYRIGHT
    - shs-libfabric/COPYING
  summary: MVAPICH, a high-performance MPI library by The Ohio State University.
  description: |
    MVAPICH is a high-performance implementation of the MPI (Message Passing Interface) standard 
    with support for **both** Unified Communication X (UCX) and Open Fabric Interfaces (OFI).

    The `_shs` variant comes with the CXI provider support for Slingshot Host Systems (use `export FI_PROVIDER=cxi` to *enable* it).

    In case the actual *netmod* is not correctly recognized at run time, activate it using either
    `MPICH_CH4_NETMOD=ucx` or `MPICH_CH4_NETMOD=ofi`.

extra:
  recipe-maintainers:
    - j34ni
