{% set mvapich_version = "4.1" %}
{% set shs_libfabric_version = "2.2.0" %}
{% set build = 1 %}

package:
  name: mvapich
  version: {{ mvapich_version }}

source:
  - url: https://mvapich.cse.ohio-state.edu/download/mvapich/mv2/mvapich-{{ mvapich_version }}.tar.gz
    sha256: a36c459befd5b0d1b66e4a217250d89d9f77b903fcc4a050efddb1c475b8dcab
    folder: mvapich
    patches:
      - fix_ucr_domain.patch
  - url: https://github.com/HewlettPackard/shs-libfabric/archive/refs/tags/v{{ shs_libfabric_version }}.tar.gz
#   sha256: ddbf61538d46ee7b5940a9206321a4361b60fcb774b9d2def6f844607c3117a5  # 2.3.0
    sha256: 734aa46fc1a5c69c59514aade3e8f17037506fbb08013f4be63d669e546570b0  # 2.2.0
    folder: shs-libfabric
    patches:
      - fix_reallocarray.patch 
      - define-map-huge-shift.patch


build:
  number: {{ build }}
  string: shs_h{{ PKG_HASH }}_{{ build }}
  skip: true  # [win or osx or linux_ppc64le]
  run_exports:
    - {{ pin_subpackage('mvapich', max_pin='x.y') }}

requirements:
  build:
    - autoconf
    - automake
    - bison
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - libtool
    - make
    - pkg-config
  host:
    - json-c
    - libcurl
    - libhwloc
    - libnl
    - rdma-core 
    - shs-cassini-headers
    - shs-cxi-drivers
    - shs-libcxi
    - ucx
  run:
    - json-c
    - libcurl
    - libhwloc
    - libnl
    - mpi 1.0.* mvapich
    - rdma-core
    - shs-cxi-drivers
    - shs-libcxi
    - ucx

test:
  requires:
    - {{ compiler('c') }}

  commands:
{% if target_platform == "linux-64" %}
    - mpiexec -n 2 $PREFIX/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency -m 1024:1024
{% else %}
    - echo "Skipping linux-aarch64 & linux-ppc64le tests for now"
{% endif %}

about:
  home: https://mvapich.cse.ohio-state.edu/
  license: BSD-3-Clause AND (BSD-2-Clause OR GPL-2.0-only)
  license_family: BSD
  license_file:
    - mvapich/COPYRIGHT
    - shs-libfabric/COPYING
  summary: MVAPICH, a high-performance MPI library by The Ohio State University.
  description: |
    MVAPICH is a high-performance implementation of the MPI (Message Passing Interface) standard 
    with support for **both** Unified Communication X (UCX) and Open Fabric Interfaces (OFI).

    The MVAPICH-SHS variant comes with the CXI provider support for Slingshot Host Systems.

    In case the actual *netmod* is not correctly recognized at run time, activate it using either
    `MPICH_CH4_NETMOD=ucx` or `MPICH_CH4_NETMOD=ofi`.

    ### About the Compilers
    Note that the actual GNU compilers (i.e., `gcc_linux-64`, `gfortran_linux-64` and `gxx_linux-64` for `linux-64`, or
    their equivalent for other platforms) have to be added manually since they are not automatically installed in the Conda
    environment as dependencies.

extra:
  recipe-maintainers:
    - j34ni
