{% set version = "3.0" %}
{% set device_variant = device if device else "default" %}

package:
  name: mvapich
  version: {{ version }}

source:
  url: https://mvapich.cse.ohio-state.edu/download/mvapich/mv2/mvapich-{{ version }}.tar.gz
  sha256: ee076c4e672d18d6bf8dd2250e4a91fa96aac1db2c788e4572b5513d86936efb

build:
  number: 0
  string: "h{{ PKG_HASH }}_{{ device_variant }}"
  skip: true  # [win or osx]
  run_exports:
    - {{ pin_subpackage('mvapich', max_pin='x.y') }}

requirements:
  build:
    - bison
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - make
  host:
    - libhwloc
    - rdma-core  # [linux]
    {% if device == "ucx" %}
    - ucx
    {% endif %}
  run:
    - mpi 1.0.* mvapich

test:
  commands:
    - mpiexec -n 2 $PREFIX/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency -m 1024:1024

about:
  home: https://mvapich.cse.ohio-state.edu/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYRIGHT
  summary: MVAPICH, a high-performance MPI library by The Ohio State University.
  description: |
    MVAPICH2 is a high-performance implementation of the MPI (Message Passing Interface) standard.
    It provides enhancements including optimization for different networking technologies.
    
    ### Important Configuration
    The default value for `MV2_ENABLE_AFFINITY` is typically `1` (enabled). This setting binds MPI processes
    to specific CPU cores to improve performance due to cache locality and reduced context switching.
    In some environments, particularly those using the Slurm job scheduler, this may degrade performances
    or lead to unexpected behavior, and hence it may be beneficial to set `MV2_ENABLE_AFFINITY=0`.

extra:
  recipe-maintainers:
    - j34ni
